name: four-phase-inversion
channels:
    - conda-forge
    - defaults
    - gimli
dependencies:
    - python=3.6
    - pygimli=1.0.11
    - pybert=2.2.10
    - seaborn
    - numpy
    - scipy
    - jupyter=1.0.0
